# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# When configured, Gradle will fork JVMs up to org.gradle.workers.max (the number of CPU processors)
# to execute projects in parallel. [Default is false]
org.gradle.parallel=true

# Allows controlling parallelism of Tooling API actions independently of task execution parallelism,
# which can improve IDE Sync times.
org.gradle.tooling.parallel=true

# When set to true, Gradle will reuse task outputs from any previous build when possible,
# resulting in much faster builds. [Default is false]
org.gradle.caching=true

# Enables configuration caching. Gradle will try to reuse the configuration from previous builds.
# [Default is false]
org.gradle.configuration-cache=true

# Enables Isolated Projects (experimental). [Default is false]
#org.gradle.unsafe.isolated-projects=true

# Kotlin code style for this project: "official" or "obsolete".
kotlin.code.style=official